### ISSUE TITLE
Update kedro 19

### ISSUE THREAD

**Issue by nickolasrm** [kedro-partitioned/kedro-partitioned#2]
Hello,

Is it possible to upgrade kedro 19 dependence in order to use it for modern kedro project ?

Thanks !

@adrienpl moved the issue to this repository

**Comment by nickolasrm** [comment]
## Story

As a user I want to be able to use Kedro partitioned features along with Kedro 0.19 so that I can keep my projects updated

### Acceptance Criteria

- [x] Identify bugs with the upgrade and fix them
- [x] Update docs if needed
- [x] Launch a new release

**Comment by adrienpl** [comment]
I can do it tomorrow if you want, I'll have time to do it
